package fabric

import (
	"fmt"
	"math/rand"
	"reflect"
	"time"
)

type Signal int

const (
	Waiting Signal = iota
	Started
	Complete
	Abort
	AbortRetry
	PartialAbort // (used to sepcify if an operation partially-completed before aborting)
)

type NodeType int

const (
	UINode NodeType = iota
	TemporalNode
	VirtualTemporalNode
	VUINode
	VirtualNode
	Unknown
)

type SignalingMap map[int]chan Signal

type SignalsMap map[int]<-chan Signal

// Dependency Graph Node
// every DGNode has an id, a Type, a state, and a set of Access Procedures
// NOTE: This will require assigning signals to their appropriate nodes
//		when setting up a dependency graph.
type DGNode interface {
	ID() int           // must be unique from all other DGNodes in our graph
	GetType() NodeType // specifies whether node is UI, VUI, etc.
	GetPriority() int  // not necessary, but can be useful
	ListProcedures() ProcedureList
	ListDependents() []DGNode
	ListDependencies() []DGNode
	ListSignalers() SignalingMap // lists signaler channels for signaling dependents
	ListSignals() SignalsMap     // lists signal channels from *dependencies*
	Signal(Signal)               // used to send the same signal to all dependents in signalers list
}

/*

AUTOGENERATED METHOD IMPLEMENTATIONS

import . "gopkg.in/check.v1"

func (d DGNode) Type() fabric.NodeType {
	var i interface{} = d
	j, ok := i.(fabric.UI)
	if ok {
		if j.IsVirtual() {
			return fabric.VUINode
		}
		return fabric.UINode
	}
	k, ok := i.(fabric.Temporal)
	if ok {
		if k.IsVirtual() {
			return fabric.VirtualTemporalNode
		}
		return fabric.TemporalNode
	}
	_, ok = i.(fabric.Virtual)
	if ok {
		return fabric.VirtualNode
	}

	return fabric.Unknown
}
*/

// Graph can be either UI DDAG, Temporal DAG or VDG
type Graph struct {
	CDS
	Nodes []DGNode
	Edges map[DGNode][]DGNode // each node (id) has a list of node ids that it points too
}

// NewGraph creates a new empty graph
func NewGraph() *Graph {
	var nodes []DGNode
	return &Graph{
		Nodes: nodes,
		Edges: make(map[DGNode][]DGNode),
	}
}

func (g *Graph) GenID() int {
	rand.Seed(time.Now().UnixNano())
	id := rand.Int()
	for _, n := range g.Nodes {
		if n.ID() == id {
			id = g.GenID()
		}
	}
	return id
}

func (g *Graph) IsLeafBoundary(n DGNode) bool {
	if len(g.Dependents(n)) == 0 {
		return true
	}

	return false
}

func (g *Graph) IsRootBoundary(n DGNode) bool {
	if len(g.Dependencies(n)) == 0 {
		return true
	}

	return false
}

func (g *Graph) CreateSignalers(n DGNode) SignalingMap {
	sm := make(SignalingMap)

	deps := g.Dependents(n)
	for _, d := range deps {
		c := make(chan Signal)
		sm[d.ID()] = c
	}

	return sm
}

func (g *Graph) Signals(n DGNode) SignalsMap {
	sm := make(SignalsMap)

	deps := g.Dependencies(n)
	for _, d := range deps {
		channels := d.ListSignalers()
		ch := channels[n.ID()]
		sm[n.ID()] = ch
	}

	return sm
}

// This should only be used for adding nodes to a graph
// to intialize the graph.
func (g *Graph) AddRealNode(node DGNode) error {
	if !contains(g.Nodes, node) {
		g.Nodes = append(g.Nodes, node)
	} else {
		return fmt.Errorf("Node already exists in Dependency Graph.")
	}
	return nil
}

func (g *Graph) AddRealEdge(source, dest DGNode) {
	if _, ok := g.Edges[source]; !ok {
		g.Edges[source] = []DGNode{dest}
	} else {
		s := g.Edges[source]
		s = append(s, dest)
		g.Edges[source] = s
	}
}

// CycleDetect will check whether a graph has cycles or not
func (g *Graph) CycleDetect() bool {
	var seen []DGNode
	var done []DGNode

	for _, v := range g.Nodes {
		if !contains(done, v) {
			result, d := g.cycleDfs(v, seen, done)
			done = d
			if result {
				return true
			}
		}
	}
	return false
}

// GetAdjacents will return the list of nodes a supplied node points too
func (g *Graph) GetAdjacents(node DGNode) []DGNode {
	return g.Edges[node]
}

// Recursive Depth-First-Search; used for Cycle Detection
func (g *Graph) cycleDfs(start DGNode, seen, done []DGNode) (bool, []DGNode) {
	seen = append(seen, start)
	adj := g.Edges[start]
	for _, v := range adj {
		if contains(done, v) {
			continue
		}

		if contains(seen, v) {
			return true, done
		}

		if result, done := g.cycleDfs(v, seen, done); result {
			return true, done
		}
	}
	seen = seen[:len(seen)-1]
	done = append(done, start)
	return false, done
}

// Totality-Uniqueness check for the UI nodes of a graph...
// should only be called once when creating the UI dependency graph;
// can be called with the creation of each UI if needed for
// more "real-time" verification.
func (g *Graph) TotalityUnique() bool {
	// grab all UI nodes
	uiSlice := make([]DGNode, 0)
	for _, v := range g.Nodes {
		if v.GetType() == UINode {
			uiSlice = append(uiSlice, v)
		}
	}

	for i, n := range uiSlice {
		// compare the UI to all other UIs
		for i2, n2 := range g.Nodes {
			if i != i2 {
				// if UI is same as other UI return false
				// i.e. graph is not totality-unique
				if reflect.DeepEqual(n, n2) {
					return false
				}
			}
		}
	}

	return true
}

// Covered returns true if all CDS nodes and edges are covered
func (g *Graph) Covered() bool {
	// grab all UI nodes
	uiSlice := make([]UI, 0)
	for _, v := range g.Nodes {
		if v.GetType() == UINode {
			uiSlice = append(uiSlice, v.(UI))
		}
	}

	// grab all CDS nodes and edges
	nodes := g.ListNodes()
	edges := g.ListEdges()

FIRST:
	// for every node in the CDS
	for _, v := range nodes {
		// check that at least one UI contains it
		for _, u := range uiSlice {
			s := u.GetSection()
			uiCDSNodes := s.ListNodes()
			// if UI contains node; check next CDS node
			if containsNode(uiCDSNodes, v) {
				continue FIRST
			}
		}
		// if CDS node is checked in every UI and does not show up
		return false
	}

SECOND:
	// for every edge in the CDS
	for _, v := range edges {
		// check that at least one UI contains it
		for _, u := range uiSlice {
			s := u.GetSection()
			uiCDSEdges := s.ListEdges()
			// if UI contains edge; check next CDS edge
			if containsEdge(uiCDSEdges, v) {
				continue SECOND
			}
		}

		// if CDS edge is checked in every UI and does not show up
		return false
	}

	return true
}

func (g *Graph) AddVUI(node UI) error {
	if !node.IsVirtual() {
		return fmt.Errorf("Not a virtual node.")
	} else {
		if !contains(g.Nodes, node) {
			g.Nodes = append(g.Nodes, node)
		} else {
			return fmt.Errorf("Node already exists in Dependency Graph.")
		}
	}
	return nil
}

func (g *Graph) RemoveVUI(node UI) error {
	newList := make([]DGNode, 0)
	if !node.IsVirtual() {
		return fmt.Errorf("Not a virtual node.")
	} else {
		for _, v := range g.Nodes {
			if node.ID() != v.ID() {
				newList = append(newList, v)
			}
		}

		g.Nodes = newList
	}

	return nil
}

func (g *Graph) AddVirtual(node Virtual) error {
	if !contains(g.Nodes, node) {
		g.Nodes = append(g.Nodes, node)
	} else {
		return fmt.Errorf("Node already exists in Dependency Graph.")
	}
	return nil
}

func (g *Graph) RemoveVirtual(node Virtual) {
	newList := make([]DGNode, 0)
	for _, v := range g.Nodes {
		if node.ID() != v.ID() {
			newList = append(newList, v)
		}
	}

	g.Nodes = newList
}

// AddVirtualEdge is the same as AddRealEdge ...
func (g *Graph) AddVirtualEdge(source, dest DGNode) {
	// Add edge to source node
	if _, ok := g.Edges[source]; !ok {
		g.Edges[source] = []DGNode{dest}
	} else {
		s := g.Edges[source]
		s = append(s, dest)
		g.Edges[source] = s
	}
}

func (g *Graph) RemoveVirtualEdge(source, dest DGNode) error {
	if v, ok := g.Edges[source]; !ok {
		return fmt.Errorf("Source node not found.")
	} else {
		if !contains(v, dest) {
			return fmt.Errorf("Edge not found.")
		}
		newList := make([]DGNode, 0)
		for _, v := range g.Edges[source] {
			if v.ID() != dest.ID() {
				newList = append(newList, v)
			}
		}
		g.Edges[source] = newList
	}
	return nil
}

func (g *Graph) Dependents(n DGNode) []DGNode {
	list := make([]DGNode, 0)
	for i, v := range g.Edges {
		if i.ID() != n.ID() {
			if contains(v, n) {
				list = append(list, i)
			}
		}
	}

	return list
}

func (g *Graph) Dependencies(n DGNode) []DGNode {
	emptyList := make([]DGNode, 0)
	if v, ok := g.Edges[n]; !ok {
		return emptyList
	} else {
		return v
	}
}

func (g *Graph) Type(n DGNode) NodeType {

	j, ok := n.(UI)
	if ok {
		if j.IsVirtual() {
			return VUINode
		}
		return UINode
	}
	k, ok := n.(Temporal)
	if ok {
		if k.IsVirtual() {
			return VirtualTemporalNode
		}
		return TemporalNode
	}
	_, ok = n.(Virtual)
	if ok {
		return VirtualNode
	}

	return Unknown
}

// FIXME: Do we need this global VUI dependents check ??
// TODO: Check that all VUIs dependents lists do not get shorter
//		over the course of their lifespan. If a dependent has ended
//		its lifecycle before a VUI finishes it's own lifespan then the
//		VUI needs to abort its operation.
func (g *Graph) CheckVUIDependents() bool {
	// TODO: check the dependents of a VUI node to be sure
	//		that they are all still in existence
	return false
}
