package ring

import (
	"github.com/JKhawaja/fabric"
)

/* Single-UI Dependency Graph code */

// TODO: This code is about defining what a UI, VUI, and Temporal object would look like
// these are the objects that are assigned to goroutines/threads in any system
// that we build and use this ring package.

type DGNode struct {
	Id               int
	Nodetype         fabric.NodeType
	Signalers        []chan fabric.Signal
	Priority         int
	AccessProcedures fabric.ProcedureList
	Dependents       []fabric.DGNode
	Dependencies     []fabric.DGNode
	Signals          []<-chan fabric.Signal
}

type RingUI struct {
	DGNode
	Section fabric.Section
	Unique  bool
	Virtual bool
}

func (r *RingUI) ID() int {
	return r.Id
}

func (r *RingUI) Type() string {
	return r.Nodetype
}

func (r *RingUI) ListSignalingChannels() []chan Signal {
	return r.Signalers
}

func (r *RingUI) GetPriority() int {
	return r.Priority
}

func (r *RingUI) ListProcedures() fabric.ProcedureList {
	return r.AccessProcedures
}

func (r *RingUI) ListDependents() []fabric.DGNode {
	return r.ListDependents()
}

func (r *RingUI) ListDependencies() []fabric.DGNode {
	return r.ListDependencies()
}

func (r *RingUI) ListSignals() []<-chan Signal {
	return r.Signals
}

func (r *RingUI) GetSection() fabric.Section {
	return r.Section
}

func (r *RingUI) IsUnique() bool {
	return r.Unique
}

func (r *RingUI) IsVirtual() bool {
	return r.Virtual
}

// Autogenerated (not in interface definition)
func (r *RingUI) SignalArrayLength() int {
	return len(r.ListDependents())
}

// Autogenerated
func (r *RingUI) IsRootBoundary() bool {
	if len(r.ListDependents()) == 0 {
		return true
	}

	return false
}

// Autogenerated
func (r *RingUI) IsLeafBoundary() bool {
	if len(r.ListDependencies()) == 0 {
		return true
	}

	return false
}
